name: pay_nav_project
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/curtain.png
    - assets/images/settings.png
    - assets/images/runner up.png
    - assets/images/second runner up.png
    - assets/images/winner.png
    - assets/images/boywithbluetick.png
    - assets/images/red triangle.png
    - assets/images/green triangle.png

